name: mobsfscan

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install mobsfscan
        run: pip install mobsfscan

      - name: mobsfscan
        run: mobsfscan . --json
